--- #YAML:1.0
name:               WordPress-Post
version:            1.06
abstract:           DEPRECATED see WordPress::CLI instead
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Simple:     0
    File::Type:       0
    Image::Magick:    0
    LEOCHARRE::CLI:   0
    MIME::Base64:     0
    Smart::Comments:  0
    XMLRPC::Lite:     0
    YAML:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
